AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rusty-bikes

  Sample SAM Template for rusty-bikes

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Cors: "'https://binhrobles.com/rusty-bikes/'"
      StageName: Prod

  ApiFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: lambda-handler
    Properties:
      CodeUri: ./services
      Handler: bootstrap    # Do not change, as this is the default executable name produced by Cargo Lambda
      Layers:
        - !Ref NYCSqliteLayer
      Runtime: provided.al2023
      Environment:
        Variables:
          DB_PATH: "/opt/lib/nyc.db3" # unzipped here by lambda layer
      Architectures:
      - x86_64
      Events:
        Traverse:
          Type: Api
          Properties:
            Path: /traverse
            RestApiId: !Ref Api
            Method: get
            RequestParameters:
            - method.request.querystring.lat:
                Required: true
            - method.request.querystring.lon:
                Required: true
            - method.request.querystring.depth:
                Required: true
        Route:
          Type: Api
          Properties:
            Path: /route
            RestApiId: !Ref Api
            Method: get
            RequestParameters:
            - method.request.querystring.start:
                Required: true
            - method.request.querystring.end:
                Required: true
            - method.request.querystring.with_traversal:
                Required: false

  NYCSqliteLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      # when a new zip is uploaded, change the name to trigger a new version / association
      LayerName: nyc-sqlite-db-5-28
      Description: Layer containing NYC SQLite DB
      ContentUri: s3://rusty-bikes-osm-data/nyc-sqlite-db-layer.zip
      CompatibleRuntimes:
        - provided.al2023

Outputs:
  RustyBikesApi:
    Description: API Gateway endpoint URL for Prod stage for Rusty Bikes API function
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ApiFunction:
    Description: API Lambda Function ARN
    Value: !GetAtt ApiFunction.Arn
  ApiFunctionIamRole:
    Description: Implicit IAM Role created for Rusty Bikes API function
    Value: !GetAtt ApiFunctionRole.Arn
