AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rusty-bikes

  Sample SAM Template for rusty-bikes

Globals:
  Function:
    Timeout: 30 # let it cook
    MemorySize: 1024
    LoggingConfig:
      LogFormat: JSON

Resources:
  OriginAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      Handler: index.handler
      MemorySize: 512
      InlineCode: |
        def handler(event, context):
            headers = event.get('headers') or {}
            origin = headers.get('origin') or headers.get('Origin', '')
            effect = 'Allow' if origin == 'https://binhrobles.com' else 'Deny'
            return {
                'principalId': 'user',
                'policyDocument': {
                    'Version': '2012-10-17',
                    'Statement': [{
                        'Action': 'execute-api:Invoke',
                        'Effect': effect,
                        'Resource': event['methodArn']
                    }]
                }
            }

  Api:
    Type: AWS::Serverless::Api
    Properties:
      Cors:
        AllowMethods: "'OPTIONS, GET, POST'"
        AllowHeaders: "'content-type'"
        AllowOrigin: "'https://binhrobles.com'"
      StageName: Prod
      Auth:
        DefaultAuthorizer: OriginAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          OriginAuthorizer:
            FunctionArn: !GetAtt OriginAuthorizerFunction.Arn
            Identity:
              Headers:
                - Origin
            AuthorizerResultTtlInSeconds: 300
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          ThrottlingBurstLimit: 20
          ThrottlingRateLimit: 10

  ApiFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: lambda-handler
    Properties:
      CodeUri: ./services
      Handler: bootstrap    # Do not change, as this is the default executable name produced by Cargo Lambda
      Layers:
        - !Ref NYCSqliteLayer
      Runtime: provided.al2023
      Environment:
        Variables:
          DB_PATH: "/opt/lib/db.db3" # unzipped here by lambda layer
      Architectures:
      - arm64 # seems to be a free lunch? https://aws.amazon.com/blogs/apn/comparing-aws-lambda-arm-vs-x86-performance-cost-and-analysis-2/
      Events:
        # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html
        Traverse:
          Type: Api
          Properties:
            Path: /traverse
            RestApiId: !Ref Api
            Method: post
        Route:
          Type: Api
          Properties:
            Path: /route
            RestApiId: !Ref Api
            Method: post
        Ping:
          Type: Api
          Properties:
            Path: /ping
            RestApiId: !Ref Api
            Method: get

  # Without these, API Gateway strips CORS headers from authorizer denial responses,
  # causing the browser to see a CORS error instead of a 403.
  GatewayResponseAccessDenied:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseType: ACCESS_DENIED
      RestApiId: !Ref Api
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'https://binhrobles.com'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'content-type'"

  GatewayResponseUnauthorized:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseType: UNAUTHORIZED
      RestApiId: !Ref Api
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'https://binhrobles.com'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'content-type'"

  NYCSqliteLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      # when a new zip is uploaded, change the name to trigger a new version / association
      LayerName: nyc-sqlite-db-2-28-26-four-boroughs
      Description: Layer containing NYC SQLite DB
      ContentUri: s3://rusty-bikes-osm-data/nyc-sqlite-db-layer.zip
      CompatibleRuntimes:
        - provided.al2023

Outputs:
  RustyBikesApi:
    Description: API Gateway endpoint URL for Prod stage for Rusty Bikes API function
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ApiFunction:
    Description: API Lambda Function ARN
    Value: !GetAtt ApiFunction.Arn
  ApiFunctionIamRole:
    Description: Implicit IAM Role created for Rusty Bikes API function
    Value: !GetAtt ApiFunctionRole.Arn
